theme = "solarized-dark"

[icons]
name = "awesome"
[icons.overrides]
memory_mem = " "
cogs = " "

[[block]]
block = "time"
interval = 60
format = "%R %a %d.%m"

[[block]]
block = "custom"
command = ''' /home/cyryl/dev/dotfiles/nixos/i3/openweathermap-fullfeatured.sh '''
interval = 600

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
speed_up = false
speed_down = false
hide_missing = true
hide_inactive = true

[[block]]
block = "cpu"
interval = 5
format = "{utilization}% {frequency}GHz"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 5
format = "{1m} {5m}"

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "kdeconnect"
format = "{name}"
format_disconnected = ""

[[block]]
block = "bluetooth"
mac = "28:11:A5:E1:3C:57"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}%"

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}%"

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{max}° max, {average}° avg"

