image: nixos/latest
sources:
  - https://git.sr.ht/~cyplo/dotfiles

secrets:
  - 6c23a8c1-7a30-4a7e-b3b7-0171e898a7d3

tasks:
  - check: |
      nix flake check
  - github_push: |
      set +xv
      cd dotfiles
      GITHUB_TOKEN=`cat ~/.github_token`
      git remote add github https://cyplo:$GITHUB_TOKEN@github.com/cyplo/dotfiles.git
      git push github --all --force
