fedora:
  script:
    - pwd
    - ls
    - $CI_PROJECT_DIR/test.sh
  image: docker:stable
  services:
    - docker:dind
  variables:
    DETECTED_OS: fedora:29
    DOCKER_IMAGE: cyplo/fedora29_base
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

ubuntu:
  script:
    - pwd
    - ls
    - $CI_PROJECT_DIR/test.sh
  image: docker:stable
  services:
    - docker:dind
  variables:
    DETECTED_OS: ubuntu:cosmic
    DOCKER_IMAGE: cyplo/cosmic_base
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
