image:fedora:
  stage: build
  script:
    - docker info
    - docker login registry.gitlab.com

image:ubuntu:
  stage: build
  script:
    - docker login registry.gitlab.com

fedora:
  before_script:
    - apk add bash
  script: ./test.sh
  image: docker:stable
  services:
    - docker:dind
  variables:
    DETECTED_OS: fedora:29
    DOCKER_IMAGE: cyplo/fedora29_base
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - image:fedora

ubuntu:
  before_script:
    - apk add bash
  script: ./test.sh
  image: docker:stable
  services:
    - docker:dind
  variables:
    DETECTED_OS: ubuntu:cosmic
    DOCKER_IMAGE: cyplo/cosmic_base
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - image:ubuntu
