#!/bin/bash

if [[ -z $DETECTED_OS ]]; then
    echo "cannot detect OS, please set DETECTED_OS manually"
    exit 1
fi

DIR=$DETECTED_OS

if [[ $DETECTED_OS =~ .*:.* ]]; then
   DIR=`echo $DETECTED_OS | cut -d':' -f1` 
else
    echo "please set DETECTED_OS to system:version"
    exit 1
fi

docker run -v `pwd`:/root/temp/dotfiles/ $DETECTED_OS /root/temp/dotfiles/$DIR/test_insider

