#!/bin/bash

set -e
set -v

sudo apt-get update
sudo apt-get -y upgrade
install_packages="sudo apt-get -y --fix-missing install apt-file aptitude aria2 atop cmake curl dkms freecad gajim git glances gnupg2 golang gparted gsmartcontrol gtk-redshift intltool kdiff3 keepass2 libatk1.0-dev libbonoboui2-dev libcairo2-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libncurses5-dev libx11-dev libxpm-dev libxt-dev linux-kernel-headers lm-sensors meld mercurial nodejs npm pv python-dev python-pip python3-pip realpath redshift retext ruby-dev silversearcher-ag terminator thunderbird thunderbird-enigmail tmux tor torsocks whois zsh libxml2-dev libxslt1-dev"

set +e
for i in `seq 1 3`; do
        eval $install_packages
done

set -e
eval $install_packages

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update
sudo apt-get -y install mono-devel mono-complete 

pushd `pwd`

if [[ -z $NO_COMPILE_VIM ]]; then
    VIM_BUILD_DIR=/tmp
    cd "$VIM_BUILD_DIR"
    git clone https://github.com/vim/vim.git
    cd vim
    ./configure --with-features=huge \
                --enable-multibyte \
                --enable-rubyinterp \
                --enable-python3interp=yes \
                --enable-luainterp \
                --enable-gui=no \
                --enable-cscope
    make -j2
    sudo make install
    cd
    rm -fvr "$VIM_BUILD_DIR/vim"
fi

popd

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR="$DIR/../../"
export NO_GO=true
export NOPYTHON3=true
DIR="$DIR" $DIR/common/configure_fresh_system
