#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
export DONT_CHANGE_SHELL=true
export NO_SYSTEMCTL=true

echo "APT::Acquire::Retries=16;" >> /etc/apt/apt.conf.d/99_retries

apt-get update
apt-get install sudo
cd $HOME

mkdir -p dev/
cp -rv temp/dotfiles dev/

# use dbus on TCP 
sudo sed -i 's$<listen>.*</listen>$<listen>tcp:host=localhost,port=0</listen>$' /etc/dbus-1/session.conf

./dev/dotfiles/ubuntu/trusty/configure_fresh_system

