version: 2

jobs:
  fedora:
    machine: true
    environment:
          DETECTED_OS: fedora:29
          DOCKER_IMAGE: cyplo/fedora29_base

    steps:
      - checkout
      - run: ./test.sh

  ubuntu:
    machine: true
    environment:
          DETECTED_OS: ubuntu:cosmic
          DOCKER_IMAGE: cyplo/cosmic_base

    steps:
      - checkout
      - run: ./test.sh

workflows:
    version: 2
    linux:
        jobs:
            - fedora
            - ubuntu
