version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    environment:
          DETECTED_OS: fedora:27
          DOCKER_IMAGE: cyplo/fedora27_base

    steps:
      - checkout
      - run: ./test.sh

