#!/bin/bash

set -e
set -v

sudo apt-get update
sudo apt-get -y upgrade
install_packages="sudo apt-get -y --fix-missing install aptitude meld whois zsh tmux atop aria2 curl pv gajim tor torsocks nodejs thunderbird thunderbird-enigmail thunderbird-ublock-origin gajim lm-sensors freecad python3-pip meld whois curl pv tor torsocks nodejs npm terminator gsmartcontrol python-pip mercurial redshift gtk-redshift cmake intltool gparted solaar glances silversearcher-ag dkms linux-kernel-headers golang keepass2 libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev ruby-dev git retext kdiff3 gnupg2 realpath apt-file"

set +e
for i in `seq 1 3`; do
        eval $install_packages
done

set -e
eval $install_packages

if [[ -z $DONT_START_TOR ]]; then
	sudo systemctl enable tor
	sudo systemctl start tor
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR="$DIR/../"
DIR="$DIR" $DIR/common/configure_fresh_system
