#!/bin/bash
set -e
set -v

#ReText
sudo aptitude -y install python3-pyqt5 python3-pip python3-pyqt5.qtwebkit
aria2c -c http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.2/sip-4.16.2.tar.gz -d /tmp
tar -C /tmp -xf /tmp/sip-4.16.2.tar.gz
cd /tmp/sip-4.16.2
python3 configure.py
make
sudo make install
sudo pip3 install retext
