#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
export DONT_CHANGE_SHELL=true
export NO_SYSTEMCTL=true
export NO_COMPILE_VIM=true

echo "APT::Acquire::Retries=16;" >> /etc/apt/apt.conf.d/99_retries

apt-get update
apt-get install sudo
cd $HOME

mkdir -p dev/
cp -rv temp/dotfiles dev/

./dev/dotfiles/debian/configure_fresh_system.sh

