{ config, pkgs, ... }:
{
  home.packages = with pkgs; [
    ( pass.withExtensions (ext: [ ext.pass-otp ext.pass-import ext.pass-genphrase ext.pass-audit ext.pass-update ]))
    apvlv
    aria
    atop
    binutils
    bitwarden-cli
    btrfs-progs
    curl
    dnsutils
    docker-compose
    du-dust
    fd
    file
    fontconfig
    genpass
    git
    hsetroot
    htop
    imagemagick
    jq
    lm_sensors
    mercurial
    nixops
    pciutils
    powertop
    ranger
    restic
    ripgrep
    rustup
    terraform
    tmux
    unzip
    veracrypt
    wget
    wirelesstools
  ];
}
