#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
export DONT_CHANGE_SHELL=true
export DONT_START_TOR=true

echo "APT::Acquire::Retries=16;" >> /etc/apt/apt.conf.d/99_retries

apt-get update
apt-get install sudo
cd $HOME
./dev/dotfiles/bunsen/configure_fresh_system

