#!/bin/bash
# detect if building inside a CI system, like Travis
set -e
echo "choosing totally noninteractive installation method"
COMMAND_PREFIX="DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::=\"--force-confdef\" -o Dpkg::Options::=\"--force-confnew\"";

curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash
sudo apt-get update
INSTALL_COMMAND="sudo $COMMAND_PREFIX install meld whois zsh tmux vim atop aria2 curl pv gajim tor torsocks nodejs terminator gsmartcontrol python-pip mesa-utils mesa-utils-extra aptitude p7zip-full p7zip-rar thunderbird mercurial kdiff3 gnupg2 python3-setuptools realpath python3-dev python3 apt-file golang"
eval ${INSTALL_COMMAND}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR="$DIR/../"
DONT_CHANGE_SHELL=TRUE DIR="$DIR" $DIR/common/configure_fresh_system

