#!/bin/bash
MOUNT_PATH="/tmp/data"
CURRENT_DIRECTORY=`pwd -P` # untangle symbolic links if needed
USERNAME=`whoami`
IMAGE="debian:jessie"

if [[ -z $1 ]]; then
    echo "usage: `basename $0` command_to_run_inside_a_container"
    exit 1
fi

RESOLVED_ARGUMENTS="$@"
docker run -i -t -v "$CURRENT_DIRECTORY":"$MOUNT_PATH":Z $IMAGE bash -c "useradd -M -d $MOUNT_PATH $USERNAME 2>&1 > /dev/null && bash -c '$RESOLVED_ARGUMENTS'"

# restore SELinux context for the current directory
restorecon -R "$CURRENT_DIRECTORY"

